import 'dart:io';
import 'package:flutter/services.dart';
import 'package:invoice/app_data/app_data.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:invoice/models/invoice_model.dart';

class ReportPdf {
  static Future<void> onDownloadReport(List<InvoiceModel> invoices) async {
    final baseFont = pw.Font.ttf(
      await rootBundle.load("assets/Fonts/Roboto-Regular.ttf"),
    );
    final boldFont = pw.Font.ttf(
      await rootBundle.load("assets/Fonts/Roboto-Bold.ttf"),
    );
    final arabicFont = pw.Font.ttf(
      await rootBundle.load("assets/Fonts/NotoSansArabic-Regular.ttf"),
    );
    final symbolsFont = pw.Font.ttf(
      await rootBundle.load("assets/Fonts/NotoSansSymbols2-Regular.ttf"),
    );
    final thaiFont = pw.Font.ttf(
      await rootBundle.load("assets/Fonts/NotoSansThai-Regular.ttf"),
    );
    final dejavu = pw.Font.ttf(
      await rootBundle.load("assets/Fonts/DejaVuSans.ttf"),
    );

    final pdf = pw.Document(
      theme: pw.ThemeData.withFont(
        base: baseFont,
        bold: boldFont,
        fontFallback: [arabicFont, symbolsFont, thaiFont, dejavu],
      ),
    );

    invoices.sort((a, b) => a.date.compareTo(b.date));
    final fromDate = invoices.first.date;
    final toDate = invoices.last.date;
    final profile = AppData().profile;
    final addressParts = [
      profile!.street,
      profile.city,
      profile.state,
      profile.country,
    ].where((e) => e.toString().trim().isNotEmpty).toList();


    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(24),
        header: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.end,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.end,
                  children: [
                    pw.Text(
                      "INVOICE SUMMARY REPORT",
                      style: pw.TextStyle(
                        fontSize: 14,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                    pw.SizedBox(height: 6),
                    pw.Text(
                      "Generated: ${DateTime.now().day}-${DateTime.now().month}-${DateTime.now().year}",
                      style: const pw.TextStyle(fontSize: 11),
                    ),
                  ],
                ),
              ],
            ),
            pw.SizedBox(height: 10),
            pw.Container(height: 1, color: PdfColors.grey600),
            pw.SizedBox(height: 8),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  profile.name,
                  style: pw.TextStyle(
                    fontSize: 22,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.blue900,
                  ),
                ),
                pw.SizedBox(height: 3),
                pw.Container(
                  width: 150,
                  child: pw.Text(
                    addressParts.isEmpty ? "" : addressParts.join(", "),
                    style: const pw.TextStyle(fontSize: 11),
                  ),
                ),
                pw.Text(profile.email, style: const pw.TextStyle(fontSize: 11)),
                pw.Text(profile.phone, style: const pw.TextStyle(fontSize: 11)),
              ],
            ),
            pw.SizedBox(height: 10),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  "Total Invoices: ${invoices.length}",
                  style: pw.TextStyle(
                    fontSize: 11,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.Text(
                  "Period: $fromDate → $toDate",
                  style: const pw.TextStyle(fontSize: 11),
                ),
              ],
            ),
            pw.SizedBox(height: 12),
          ],
        ),

        footer: (context) => pw.Center(
          child: pw.Text(
            "Generated by eZInvoice Generator • Page ${context.pageNumber}/${context.pagesCount}",
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ),

        build: (context) {
          final headers = ["No", "Customer / Company", "Date", "Amount"];
          final rows = invoices.asMap().entries.map((entry) {
            final index = entry.key + 1;
            final e = entry.value;
            return [
              index.toString(),
              e.billTo.trim().split("\n").first,
              e.date,
              "${e.currencySymbol ?? '\$'} ${e.total.toStringAsFixed(2)}",
            ];
          }).toList();
          final total = invoices.fold<double>(0, (sum, e) => sum + e.total);

          return [
            pw.Container(
              decoration: pw.BoxDecoration(
                borderRadius: pw.BorderRadius.circular(4),
                border: pw.Border.all(color: PdfColors.grey400),
              ),
              child: pw.Table.fromTextArray(
                headers: headers,
                data: rows,
                border: null,
                headerDecoration: pw.BoxDecoration(color: PdfColors.blue100),
                headerStyle: pw.TextStyle(
                  fontSize: 12,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.blue900,
                ),
                headerHeight: 28,
                cellStyle: const pw.TextStyle(fontSize: 11),
                cellHeight: 25,
                cellAlignment: pw.Alignment.centerLeft,
                headerAlignments: {
                  0: pw.Alignment.center,
                  1: pw.Alignment.center,
                  2: pw.Alignment.center,
                  3: pw.Alignment.centerRight,
                },
                cellAlignments: {
                  0: pw.Alignment.center,
                  1: pw.Alignment.center,
                  2: pw.Alignment.center,
                  3: pw.Alignment.centerRight,
                },
                oddRowDecoration: pw.BoxDecoration(color: PdfColors.grey200),
                columnWidths: {
                  0: pw.FlexColumnWidth(0.5),
                  1: pw.FlexColumnWidth(3),
                  2: pw.FlexColumnWidth(1),
                  3: pw.FlexColumnWidth(1),
                },
              ),
            ),

            pw.SizedBox(height: 20),

            pw.Align(
              alignment: pw.Alignment.centerRight,
              child: pw.Container(
                padding: const pw.EdgeInsets.all(10),
                width: 200,
                decoration: pw.BoxDecoration(
                  color: PdfColors.blue50,
                  borderRadius: pw.BorderRadius.circular(4),
                  border: pw.Border.all(color: PdfColors.blue400),
                ),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(
                      "GRAND TOTAL:",
                      style: pw.TextStyle(
                        fontSize: 12,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                    pw.Text(
                      "${invoices.first.currencySymbol ?? '\$'} ${total.toStringAsFixed(2)}",
                      style: pw.TextStyle(
                        fontSize: 12,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ];
        },
      ),
    );

    /// Save PDF to Downloads
    Directory dir = Directory("/storage/emulated/0/Download");
    final now = DateTime.now();
    final formatted =
        "${now.year}-${now.month}-${now.day}_${now.hour}-${now.minute}-${now.second}";
    final file = File("${dir.path}/Invoice_Report_$formatted.pdf");
    await file.writeAsBytes(await pdf.save());
    print("PDF saved to: ${file.path}");
  }
}
